name: Build pdfs

on:
  workflow_dispatch:
  
jobs:
  build_pdfs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            ./build.sh
      - uses: actions/upload-artifact@v3.1.0
        with:
          name: pdf-artifacts
          path: ./*.pdf
